### PR TITLE
Fix copyright owner

### PR DESCRIPTION
**Pull request by willkg**
All work we do is for the Mozilla Foundation. This fixes that.

### CODE REVIEW

**Comment by sole** [comment]
Thanks for the fix!

Do you know where is this stated? I'd be curious to know about it for the future. Pretty sure wherever says "Mozilla Foundation" must be used might have more interesting data that I should know about.

**Comment by willkg** [comment]
Pretty sure it's in our employment contracts, but I can't find mine at the moment.

**Comment by tofumatt** [comment]
What does @gerv or someone else familiar with our copyright setup say?

**Comment by sole** [comment]
I'm trusting @willkg but we should maybe ping @gerv yeah!

**Comment by sole** [comment]
I've written to Gervase. I'll update with his response.

**Comment by gerv** [comment]
Mozilla Foundation is correct if all contributors are employees. As soon as any are not, it becomes incorrect - but then so are most copyright notices on open source software all across the world :-\ If you care, when that happens you could change it to "Mozilla Contributors", which is accurate.

**Comment by tofumatt** [comment]
Oh, thanks for the heads-up! I’ll start using "Mozilla Contributors” in the future.

**Pull request merged**
